# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'surveyapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for surveyapp
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'
  pod 'ReactNativeKeyboardManager', :path => '../node_modules/react-native-keyboard-manager'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

end
